#!/bin/bash
#
# Test cmpds.py using data generated by gends.py.
#

# ================================================================
#
# Functions
#
# ================================================================
function passed_fct() {
    local tid="$1"
    local ctxt=($(caller 0))
    local ln=$(( ${ctxt[0]} - 2 ))
    (( Total++ ))
    (( Passed++ ))
    printf 'test:%02d:%03d: passed - %s\n' $Total $ln "$tid"
}

function failed_fct() {
    local tid="$1"
    local ctxt=($(caller 0))
    local ln=$(( ${ctxt[0]} - 4 ))
    (( Total++ ))
    (( Failed++ ))
    printf 'test:%02d:%03d: failed - %s\n' $Total $ln "$tid"
}

# ================================================================
# Main.
# ================================================================
Passed=0
Failed=0
Total=0
GenDS=./gends.py
CmpDS=../cmpds.py

# Test 1. Identical.
tid='no change'
printf '\ntest %s\n' "$tid"
ds1=$$.txt
ds2=$ds1
$GenDS 50 120 122 > $ds1
if $CmpDS $ds1 $ds2 | grep 'no significant difference' ; then
    passed_fct "$tid"
else
    failed_fct "$tid"
fi
rm -f $ds1 $ds2

# Test 2. dataset 2 is smaller, CL = 95%
tid='dataset-2 is smaller, CL=95%'
printf '\ntest %s\n' "$tid"
ds1=$$-1.txt
ds2=$$-2.txt
$GenDS 50 120 122 > $ds1
$GenDS 50 118 120 > $ds2
if $CmpDS $ds1 $ds2 | grep 'dataset-2 is smaller' ; then
    passed_fct "$tid"
else
    failed_fct "$tid"
fi
rm -f $ds1 $ds2

# Test 3. dataset 2 is larger, CL = 95%
tid='dataset-2 is larger, CL=95%'
printf '\ntest %s\n' "$tid"
ds1=$$-1.txt
ds2=$$-2.txt
$GenDS 50 118 120 > $ds1
$GenDS 50 120 122 > $ds2
if $CmpDS $ds1 $ds2 | grep 'dataset-2 is larger' ; then
    passed_fct "$tid"
else
    failed_fct "$tid"
fi
rm -f $ds1 $ds2

# Test 4. dataset 2 is smaller, CL = 90%
tid='dataset-2 is smaller, CL=90%'
printf '\ntest %s\n' "$tid"
ds1=$$-1.txt
ds2=$$-2.txt
$GenDS 50 120 122 > $ds1
$GenDS 50 118 120 > $ds2
if $CmpDS -c 0.90 $ds1 $ds2 | grep 'dataset-2 is smaller' ; then
    passed_fct "$tid"
else
    failed_fct "$tid"
fi
rm -f $ds1 $ds2

# Test 5. dataset 2 is larger, CL = 90%
tid='dataset-2 is larger, CL=90%'
printf '\ntest %s\n' "$tid"
ds1=$$-1.txt
ds2=$$-2.txt
$GenDS 50 118 120 > $ds1
$GenDS 50 120 122 > $ds2
if $CmpDS -c 0.90 $ds1 $ds2 | grep 'dataset-2 is larger' ; then
    passed_fct "$tid"
else
    failed_fct "$tid"
fi
rm -f $ds1 $ds2

# Test 6. example 1 - two datasets in one file
tid='exmple-1 two datasets in one file'
printf '\ntest %s\n' "$tid"
ds='example1.ds'
if $CmpDS -k 2 3 $ds | grep 'dataset-2 is smaller' ; then
    passed_fct "$tid"
else
    failed_fct "$tid"
fi

# Summary:
echo
printf "test:summary passed %2d\n" $Passed
printf "test:summary failed %2d\n" $Failed
printf "test:summary total  %2d\n" $Total

if (( $Failed )) ; then
    echo "FAILED"
else
    echo "PASSED"
fi
exit $Failed

